### ISSUE TITLE
Error while browsing movie list (special characters?)

### ISSUE THREAD

**Issue by evertiro** [kasamedia/plugin.video.specialfeatures#1]
> Cross-posted from old repo.

I'm using Special Features 3.0.1 on Kodi 17.6 with default db SQlite (not MySQL). In plugin configuration, I have configured Enable Context Menu.

When browsing my movie collection, I receive an error popup from Special Features hinting to the log. Here is the log:

```
19:22:26.837 T:14660    INFO: : QUERYING DATABASE
19:22:26.846 T:14660   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'sqlite3.ProgrammingError'>
                                            Error Contents: You must not use 8-bit bytestrings unless you use a text_factory that can interpret 8-bit bytestrings (like text_                                            Traceback (most recent call last):
                                              File "C:\Users\Christian\AppData\Roaming\Kodi\addons\plugin.video.specialfeatures\service.py", line 16, in <module>
                                                dbEnterExit().initDb('quikchk2')
                                              File "C:\Users\Christian\AppData\Roaming\Kodi\addons\plugin.video.specialfeatures\lib\iteration.py", line 223, in initDb
                                                self.queryDb('quikchk2')
                                              File "C:\Users\Christian\AppData\Roaming\Kodi\addons\plugin.video.specialfeatures\lib\iteration.py", line 558, in queryDb
                                                self.entry = self.sql.exeCute('fw_special',self.fnp,'one')
                                              File "C:\Users\Christian\AppData\Roaming\Kodi\addons\plugin.video.specialfeatures\lib\querylib.py", line 63, in exeCute
                                                cu.execute(self.command,(var,))
                                            ProgrammingError: You must not use 8-bit bytestrings unless you use a text_factory that can interpret 8-bit bytestrings (like tex                                            -->End of Python script error report<--
19:22:26.872 T:14660    INFO: Python script stopped
```

After the error message, the context menu entry for Special Features is missing.

I have some movies with special characters in their title and path which possibly leads to the error:

![](https://user-images.githubusercontent.com/7452817/38207031-be4ecad8-36ac-11e8-845c-d914e8f0113f.png)

**Comment by evertiro** [comment]
@git-developer Copied https://github.com/smitchell6879/plugin.video.specialfeatures/issues/37 to our new repo. Please post updates in this issue.

**Comment by evertiro** [comment]
Note that the above commit was not intended to tag this issue.

**Comment by evertiro** [comment]
Replicated this issue

**Comment by evertiro** [comment]
@smitchell6879 This can be replicated on `master` by creating a valid movie directory/file in a language which uses non-latin characters. I used Monty Python in my tests:

```Monty Python die Ritter der Kokosnuß (1978)```

With the `master` branch, this throws an error when browsing the movie list (whether or not SF has performed a scan), and causes a fatal error when the SF menu entry for the non-latin movie is selected after scanning. The `issue/1` branch fixes both issues.
